### PR TITLE
Update invoice items to current collmex field names

### PR DESCRIPTION
**Pull request by zagy**

### CODE REVIEW

**Comment by zagy** [comment]
Cannot run the tests due to gpg/credentials.

**Comment by icemac** [comment]
Locally the Python 3.11 tests ran successfully.

What is the reason behind this PR? Why/where it is needed?

**Comment by zagy** [comment]
The invoice API has more/different fields now. So I pulled the current names from the API docs and updated the field list.

**Comment by icemac** [comment]
Thank you for this PR. 😃

**Pull request merged**
